package range;

dialect "java" 

import java.util.*
import org.jannocessor.model.*
import org.jannocessor.domain.*;
import org.jannocessor.domain.executable.*;
import org.jannocessor.domain.type.*;
import org.jannocessor.domain.variable.*;

global ProcessingContext context

rule "Annotations"
when
	clazz : JavaClass()
then
	context.getProcessors().process("Annotations", context, new Object[] { clazz });
end

rule "Wrong annotations"
when
	field : JavaField()
then
	context.getProcessors().process("Wrong annotations", context, new Object[] { field });
end
