#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
package ${package}.example.test;
import ${package}.example.model.Book;
import ${package}.example.model.BookBuilder;
import ${package}.example.model.Person;
import ${package}.example.model.PersonBuilder;

public class GeneratedBuildersApp {

	/**
	 * A PoC application that shows the builders were generated correctly and behave well.
	 */
	public static void main(String[] args) {
		// the PersonBuilder and BookBuilder classes should be generated by running "mvn install"
		Person person = new PersonBuilder().firstName("John").lastName("Doe").build();
		Book book = new BookBuilder().author(person).title("Jannocessor").build();

		System.out.println(book);
	}
}
